## 10장 예외

<br>

### 예외는 진짜 예외 상황에만 사용하라

**예외를 잘못 사용한 예**
```java
try {
	int i = 0;
	while (true) 
		range[i++].climb();
} catch (ArrayIndexOutOfBoundsException e) {...}
```
- `range`라는 배열을 무한루프를 돌며 순회하는데 순회의 종료 조건을 예외로 하고 있다.
- 배열의 경우 매번 범위에 대한 검사를 수행한다. 
  `ArrayIndexOutOfBoundsException`가 발생하는 경우 순회를 종료하는 것이다.

위 코드를 사용한 이유가 나름 있을 수 있지만 일단 가독성이 떨어지고 일반적인 for문을 사용하는 것보다 느리다고 한다. 굳이 사용할 이유가 없는 것이다.

#### 예외는 오직 예외상황에서만 써야 한다. 절대 일상적인 제어 흐름용으로 쓰지 말자.
#### 클라이언트의 정상적 요청으로 정상적 제어 흐름이 흘러가는 중에 예외가 발생할 일이 없게 해야 한다.

***

### 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라

`CheckedExcetpion`, `RuntimeException`, `Error`를 언제 사용해야 하는가?

#### 호출하는 쪽에서 복구하리라 여겨지는 상황이라면 검사 예외를 사용하라.
- 위 규칙이 검사, 비검사 예외를 구분하는 **기본 규칙**이다.
- 검사 예외를 던지면 호출한 쪽에서 `try-catch`로 처리하거나 `throws`로 밖으로 전파시킨다.
- **검사예외** : 해당 메서드를 호출했을 때 발생할 수 있는 유력한 결과임을 알려주는 것

#### 비검사 - 런타임 예외, 에러
- 두 예외는 잡을 필요가 없거나 잡지 말아야 한다.
- **비검사 예외**나 **에러**가 던져진 것은 복구가 불가능하거나 더 실행하는 것에 의미가 없다는 것이다.
- 에러를 잡거나 복구하는 대신 오류 메시지를 던지며 **중단**된다.

#### 프로그래밍 오류를 나타날 때는 런타임 예외를 사용하자.
- `런타임 예외`는 대부분 클라이언트가 API의 명세를 지키지 못했을 때 발생한다.
  ex) `ArrayIndexOutOfBoundsException`


어떤 조건에서 문제로 예외가 발생했을 때 복구할 수 있는 상황인지 그렇지 않은 상황인지 명확히 구분하기 힘들 수 있다.

**자원 고갈**의 경우 너무 큰 크기의 배열을 할당해서 생긴 프로그래밍 오류일 수 있고 정말 자원이 부족해서 발생한 문제일 수도 있다.

만약 순간적으로 자원이 몰린 것 때문에 발생하는 상황이라면 복구 가능할 것이다.
하지만 애초에 너무 큰 크기의 배열이 할당되서 발생했다면 이후 복구할 여지가 없다.

복구가 가능하다면? **검사 예외**
복구가 가능하지 않다면? **런타임 예외**

#### 직접 구현하는 비검사 throwable은 모두 RuntimeException의 하위 클래스여야 한다.
- `Error`는 상속해서 예외 클래스를 만드는 것은 자제하자.
- 이는 널리 퍼진 규약이다.
- `Error`는 상속하지 말고 `throw`로 던지지도 말자.

#### throwable 은 언제 사용하면 좋은가?
- 사용하지 말자.
- `throwable` 은 정상적인 검사 예외보다 좋은게 없다. 그냥 사용하지 말자.


> 정리
복구 가능한 상황 => 검사 예외
프로그래밍 오류 => 비검사 예외 (RuntimeException)
애매하다면 => 비검사 예외
검사 예외도 런타임 예외도 아니라면 `throwable`은 사용하지 말자

***

### 필요 없는 검사 예외 사용은 피하라
- **검사 예외**는 발생한 문제를 클라이언트가 처리하게 하여 안전성을 높일 수 있다.
- **but,** 과한 **검사 예외**의 사용은 API를 사용하기 불편하게 할 수 있다.
  호출하는 쪽에서 `try-catch` 또는 `throws`를 강제하기 때문이다.
- 검사 예외를 던지는 API는 스트림 안에서 직접 사용할 수 없다..

API를 제대로 사용해도 발생할 수 있는 예외나 의미있는 조치가 가능한 경우가 아니라면
**비검사 예외** 를 사용하자.


#### 검사 예외를 회피하는 가장 쉬운 방법
- 적절한 결과 타입을 담은 `Optional`을 반환하는 것
  `검사예외` 대신 `빈 Optional`을 반환하는 것이다.
- `검사예외`를 회피할 수 있지만 어떤 예외인지에 대한 정보를 담을 수 없다.

#### 검사 예외를 발생하는 메서드르 2개로 쪼개 비검사 예외로 바꾸는 방법
첫번째 메서드에서 **예외가 발생할 지에 대한 여부**를 `boolean`으로 반환   

```java
// 검사예외를 그대로 던지는 메서드
try {
	obj.action(args);
} catch (TheCheckedException e) {
	// 예외처리 ...
}

// 메서드의 상태를 검사하고 비검사 예외를 던지는 메서드
if (obj.actionPermitted(args)) {
	obj.action(args);
} else {
	// 예외처리 ...
}
```

모든 상황에서 메서드의 예외발생 가능 상황을 검사할 수는 없지만 가능하다면 적용하여 편한 API를 만들 수 있다.

> 정리
**검사 예외**는 API의 안전성을 높여준다.
하지만 API를 사용하기 불편하게 만든다. (try-catch, throws ㅠㅠ)
호출하는 쪽에서 예외를 복구할 방법이 없다면 **비검사 예외**를 던져주자.
예외에 대해 호출자가 어떤 처리를 해주길 바란다면 우선 **빈 Optional**을 반환해도 될지 고민하자.
예외에 대한 충분한 정보를 전달해야 한다면 **검사예외**를 던지자.

***

### 표준 예외를 사용하라

> 숙력된 프로그래머는 그렇지 못한 프로그래머보다 더 많은 코드를 재사용한다. !!

#### `IllegalArgumentException`
- 호출하는 쪽에서 부적절한 인자를 넘겼을 때 던지는 예외
- 사용하려는 객체가 메서드를 수행하기에 부족할 때, 제대로 초기화되지 않았을 때 사용한다.
- 메서드에서 발생하는 모든 예외를 `IllegalArgumentException`로 할 수도 있지만 보통 상황에 따라 분리해서 사용한다.
  ex) `NullPointException`, `IndexOutOfBoundsException`

`NullPointException`
- `null`을 허용하지 않는 메서드에 `null`이 전달됐을 때에는 `IllegalArgumentException` 보다는 `NullPointException` 를 사용한다.

#### `ConcurrentModificationException`
- 단일 쓰레드에서 사용하려한 객체를 **여러 쓰레드에서 동시에 수정**할 때 던지는 예외
- 동시에 수정하는 것을 확실하게 감지하는 방법은 없다. 단지 문제가 동시 수정 문제가 생길 가능성을 알려주는 역할을 한다.

#### Exception, RuntimeException, Throwable, Error는 직접 재사용하지 말자 !!!
- 여러 표준 예외의 추상 클래스라고 생각하자.

<br>

> 정리
인수값이 무엇이든 어차피 실패하는 경우라면 `IllegalStateException`
그렇지 않은 경우에는 `IllegalArgumentException`
을 사용하자.

***

### 추상화 수준에 맞는 예외를 던지라

수행하려는 일과 관련 없어 보이는 예외가 발생되는 경우가 있다.
메서드가 `저수준 예외`를 처리하지 않고 `throws` 해버린 경우 발생가능한 일이다.

#### 상위 계층에서는 저수준 예외를 잡아 자신의 추상화 수준에 맞는 예외로 바꿔 던져야 한다.
```java
try {
	...
} catch (LowerLevelException e) {
	throw new HigherLevelException(...);
}
```

`저수준 예외`가 디버깅 등에 도움이 되는 상황이라면 **예외 연쇄**를 사용한다.
```java
try {
	...
} catch (LowerLevelException cause) {
	throw new HigherLevelException(cause);
}
```

#### 무작정 예외를 전파는 것보다 예외 번역이 좋은 방법이지만, 남용하는 것은 곤란하다.
- 일단 하위 계층의 메서드에서 예외가 발생하지 않도록 하는 것이 최선이다.
- 상위 계층에서 하위 계층의 메서드를 사용할 때 검증과정을 거치는 것으로 하위 계층 메서드에서 예외가 발생하는 것을 막을 수 있다.

> 정리
하위 계층에서 발생한 예외를 상위 계층으로 던져야만 한다면 **예외 번역**을 사용하자.
**예외 연쇄**를 함께 사용하면 **저수준 예외**와 함께 **상위 계층에 어울리는 고수준 예외**를 만들어서 던질 수 있다.

***

### 예외의 상세 메시지에 실패 관련 정보를 담으라
예외를 잡지 못하고 프로그램이 실패되는 경우 해당 예외의 `스택 추적 정보`를 자동으로 출력한다.

`스택 추적 정보`는 예외 객체의 `toString`의 결과가 담기게 되고 보통 예외 클래스 명 뒤 상세 메시지가 붙는다.

`toString`에 실패 원인에 대한 정보를 최대한 많이 담는 것이 중요하다.

#### 실패 순간을 포착하려면 발생한 예외에 관여한 모든 매개변수, 필드 값을 메시지에 담아야 한다.
`IndexOutOfBoundsException` 을 예로 들면 **범위의 최솟값, 최댓값**, **인덱스 값** 등을 메시지에 담아야 한다.


장황하지 않는 선에서 관련된 데이터를 모두 담자.

***

### 가능한 한 실패 원자적으로 만들라

> **실패 원자적** 
호출된 메서드가 실패하더라도 해당 객체는 메서드 호출 전 상태를 유지해야 한다.

예외가 발생된 경우에도 해당 객체는 여전히 사용 가능한 상태로 남긴다.

#### 불변 객체는 태생적으로 실패 원자적이다.
객체를 **실패 원자적** 으로 만들고 싶다면 객체를 불변으로 설계하자.

> 불변 클래스의 조건
1. 객체의 상태를 변경하는 메서드를 제공하지 않는다. - `setter` XXX
2. 클래스를 확장(상속)할 수 없도록 한다. - `final 클래스`
3. 모든 필드는 `final`로 선언한다.
4. 모든 필드는 `private`로 선언한다.
5. 외부에 내부 가변 컴포넌트에 접근해야 한다면 반드시 `방어적 복사`를 사용하자.

불변 객체의 상태는 **생성 시점에 고정**되기 때문에 메서드가 실패해도 해당 객체는 불안정한 상태에 빠지지 않는다.

#### 가변 객체를 실패 원자적으로 만드는 방법
매개변수에 대한 유효성 검증을 수행하자.
객체의 내부 상태를 변경하기 전에 예외의 가능성을 방지하는 방법이다.

```java
// 유효성 검증 예
public Object pop() {
	if (size == 0) throw new EmptyStackException();
	Object result = elements[--size];
	elements[size] = null;
	return result;
}
```

#### 임시 복사본에서 작업 후 작업 성공시 원본 객체와 교체하는 방법
임시 자료구조에서 저장해서 작업하는 것이 더 빠른 경우 적용하면 좋은 방법이다.

정렬을 위한 메서드의 매개변수로 `리스트`가 전달됐을 때 `리스트`를 `배열`로 옮겨서 정렬을 수행할 수 있다.

배열을 사용하면 반복문 내에서 보다 빠르게 원소에 접근할 수 있기 때문이다.

성능상 유리한 것도 있지만 만약 **정렬에 실패**하더라도 `원본 입력 리스트`에는 전혀 영향이 없다.


> **실패 원자성**은 권장되지만 항상 달성할 수 있는 것도, 해야 하는 것도 아니다.
불가능한 경우가 있고, 가능하지만 그 비용이나 복잡도가 매우 크다면 고민해봐야 한다.


***

### 예외를 무시하지 말라.

`빈 catch` 블록에 주의하자.
`빈 catch` 블록은 예외에 대해 아무런 대처를 하지 않는다. 고로 존재 이유가 없다.

하지만, 예외를 무시해야 하는 경우도 있다.
`FileInputStream`을 닫을 때 파일의 상태를 변경하지 않을 것이고 이미 필요한 정보는 모두 읽은 상태일 것이므로 따로 복구해야 할 것이 없다.

#### 예외를 무시하기로 했다면 `catch` 블록 안에 이유를 남기고 예외 변수의 이름을 `ignored`로 하자.

```java
try {
	...
} catch (ExecutionException ignored) {
	// 예외 무시 이유 ....
}
```

> 빈 catch 블록은 오류를 내제한 채 동작하게 된다.
이유를 알 수 없이 갑자기 죽어버릴 수도 있다. 
예외를 무시하지 말고 최소한 바깥으로 던지기라도 하자.